### ISSUE TITLE
Add the possibility to "put" and "get" predefined panels with ready-to-use plots

### ISSUE THREAD

**Issue by nunoguedelha** [ami-iit/yarp-openmct#151]
The feature can be implemented in two steps. The user actions mentioned below would be performed through the client GUI on the browser.:
- [x] #160
    Provide to the user a folder in the telemetry visualiser app repository where the user could save exported predefined panels (`json` files). Such panels would then be made available on the client visualiser on the browser, among the other telemetry entries.
    <details>
    <summary>Example of json exported panel</summary>
    
    ```json
    {
      "openmct": {
        "4edc453c-8535-4912-897c-36c3028e7778": {
          "composition": [{
            "namespace": "",
            "key": "ee9c1e48-9e89-4b87-8fd2-0652919d514f"
          }, {
            "namespace": "",
            "key": "1e30f98b-c3e1-4ea7-8f82-a93c40ac0f4f"
          }, {
            "namespace": "",
            "key": "ec67ddff-b798-4b30-8023-152bd8747f9c"
          }],
          "configuration": {},
          "name": "Right Upper Leg Tracking",
          "type": "telemetry.plot.stacked",
          "location": "mine",
          "modified": 1661529970146,
          "persisted": 1661529955896,
          "id": "4edc453c-8535-4912-897c-36c3028e7778",
          "identifier": {
            "namespace": "",
            "key": "4edc453c-8535-4912-897c-36c3028e7778"
          }
        },
        "ee9c1e48-9e89-4b87-8fd2-0652919d514f": {
          "composition": [{
            "namespace": "yarpopenmct.vectorCollectionsTelemetry",
            "key": "walkingController.logger",
            "index": "0"
          }, {
            "namespace": "yarpopenmct.vectorCollectionsTelemetry",
            "key": "walkingController.logger",
            "index": "1"
          }],
          "configuration": {
            "series": [{
              "identifier": {
                "namespace": "yarpopenmct.vectorCollectionsTelemetry",
                "key": "walkingController.logger",
                "index": "0"
              },
              "yKey": "value.joints_state::positions::desired.26"
            }, {
              "identifier": {
                "namespace": "yarpopenmct.vectorCollectionsTelemetry",
                "key": "walkingController.logger",
                "index": "1"
              },
              "yKey": "value.joints_state::positions::measured.26"
            }],
            "yAxis": {},
            "xAxis": {},
            "filters": {}
          },
          "name": "Right Hip Pitch Tracking",
          "type": "telemetry.plot.overlay",
          "location": "4edc453c-8535-4912-897c-36c3028e7778",
          "modified": 1661529760851,
          "id": "ee9c1e48-9e89-4b87-8fd2-0652919d514f",
          "persisted": 1661529760851,
          "identifier": {
            "namespace": "",
            "key": "ee9c1e48-9e89-4b87-8fd2-0652919d514f"
          }
        },
        "1e30f98b-c3e1-4ea7-8f82-a93c40ac0f4f": {
          "composition": [{
            "namespace": "yarpopenmct.vectorCollectionsTelemetry",
            "key": "walkingController.logger",
            "index": "0"
          }, {
            "namespace": "yarpopenmct.vectorCollectionsTelemetry",
            "key": "walkingController.logger",
            "index": "1"
          }],
          "configuration": {
            "series": [{
              "identifier": {
                "namespace": "yarpopenmct.vectorCollectionsTelemetry",
                "key": "walkingController.logger",
                "index": "0"
              },
              "yKey": "value.joints_state::positions::desired.27"
            }, {
              "identifier": {
                "namespace": "yarpopenmct.vectorCollectionsTelemetry",
                "key": "walkingController.logger",
                "index": "1"
              },
              "yKey": "value.joints_state::positions::measured.27"
            }],
            "yAxis": {},
            "xAxis": {},
            "filters": {}
          },
          "name": "Right Hip Roll Tracking",
          "type": "telemetry.plot.overlay",
          "location": "4edc453c-8535-4912-897c-36c3028e7778",
          "modified": 1661529770660,
          "id": "1e30f98b-c3e1-4ea7-8f82-a93c40ac0f4f",
          "persisted": 1661529770660,
          "identifier": {
            "namespace": "",
            "key": "1e30f98b-c3e1-4ea7-8f82-a93c40ac0f4f"
          }
        },
        "ec67ddff-b798-4b30-8023-152bd8747f9c": {
          "composition": [{
            "namespace": "yarpopenmct.vectorCollectionsTelemetry",
            "key": "walkingController.logger",
            "index": "0"
          }, {
            "namespace": "yarpopenmct.vectorCollectionsTelemetry",
            "key": "walkingController.logger",
            "index": "1"
          }],
          "configuration": {
            "series": [{
              "identifier": {
                "namespace": "yarpopenmct.vectorCollectionsTelemetry",
                "key": "walkingController.logger",
                "index": "0"
              },
              "yKey": "value.joints_state::positions::desired.28"
            }, {
              "identifier": {
                "namespace": "yarpopenmct.vectorCollectionsTelemetry",
                "key": "walkingController.logger",
                "index": "1"
              },
              "yKey": "value.joints_state::positions::measured.28"
            }],
            "yAxis": {},
            "xAxis": {},
            "filters": {}
          },
          "name": "Right Hip Yaw Tracking",
          "type": "telemetry.plot.overlay",
          "location": "4edc453c-8535-4912-897c-36c3028e7778",
          "modified": 1661529781095,
          "id": "ec67ddff-b798-4b30-8023-152bd8747f9c",
          "persisted": 1661529781095,
          "identifier": {
            "namespace": "",
            "key": "ec67ddff-b798-4b30-8023-152bd8747f9c"
          }
        }
      },
      "rootId": "4edc453c-8535-4912-897c-36c3028e7778"
    }
    ```
    
    </details>
- [x] ~**Allow the user to save/export a custom panel, just created, to the remote server exchange folder.**~
- [ ] #159
      Build dictionary and `StaticImportObjectPlugin ` install instances automatically from `exchange` contents.

**Comment by nunoguedelha** [comment]
## Allow the user to access, from the visualizer client, exported panels stored in the remote server exchange folder

The plugin implementing this behaviour could have been implemented within the openmct framework directly, next to the plugin `staticRootPlugin`, but we implement it in `yarp-openmct` for now, for not further diverging from the official openmct release, as previous fixes/developments are still to be submitted.

The implementation steps are:
- [ ] copy `staticRootPlugin` implementation code from Open-MCT module to folder [`openmctStaticServer/plugins/staticImportObjectPlugin`](../tree/feature/ami151-access-predefined-panels-through-server/openmctStaticServer/plugins/staticImportObjectPlugin)
- [ ] Replace AMD module definition (`define` function) by ECMA Script Javascript module definition (`import` primitives) (refer to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules)

    Different module specifications:
    - CommonJS: commonly used on **Node.js**, characterized by the use of `module.exports` and `require()`.
    - AMD: commonly used on browser code, characterized by the use of `define[]()` and `import`.
    - ECMA Script (ES6): natively supported and commonly used on browser code, characterized by the use of `export` or `export default`  and `import`.

- [ ] Add as input an arbitrary location folder.
