### ISSUE TITLE
Process SIGINT, SIGTERM, SIGQUIT signal events for iCubTelemVizServer Node.js process.

### ISSUE THREAD

**Issue by nunoguedelha** [ami-iit/yarp-openmct#40]
## Processing the SIGINT event: closeServers(signal) function

The function `closeServers(signal)` implements the following ordered sequence of closure actions:
- [x] #60  
    - [x] Implement the Promise/Resolve/Reject pattern for synchronizing the closure steps (refer to https://github.com/ami-iit/yarp-openmct/issues/40#issuecomment-948071878).
    - [x] A.1 - Stop the child Node.js process running the OpenMCT static server which served the installation of the telemetry web client (visualizer web GUI). => #41 
    - [x] A.2 - Stop the Telemetry HTTP server `telemServer` from accepting new connections from the still running client web page.
    - [x] A.3 - Stop the Control Console HTTP server `consoleServer` from accepting new connections.
- [x] #53
    - [x] B - Stop listening to client requests ("subscribe"/"unsubscribe" events) on the open websockets.
- [x] #54
    - [x] Close the respective YARP port connections and YARP ports instantiated by the main Node.js process.
    - [x] Stop reading the YARP ports associated to the telemetry entries in `portInConfig` (turn off the respective listeners).
    - [x] Stop sending "real-time telemetry data" messages (notifications) to subscribers, i.e. remove the subscriptions.
    - [x] ~Complete the unfinished processing or responses to the pending requests. => **use "drain"**~
    - [x] Close all websockets.
- [x] ~#55~

non-ticked points just need to be integrated into the Promise/resolve pattern.

___

- [x] #57 
- [ ] #59 
___

- #78 **(NOT TREATED IN THIS EPIC)**
    - Stop the Control Console HTTP server `consoleServer` from accepting new RPC commands from the control console web client.
    - Stop an eventual ongoing "ping" process.
    - Execute any command required to safely stop any ongoing operation (e.g. "pause walking" if the robot was on a walking cycle).
    - Complete the unfinished processing or responses to the pending commands.
    - Close the respective YARP RPC port connections and RPC read ports instantiated by the main Node.js process.

___

- [x] #61 . This should be automatic if there is no pending queued events in the Node Event Loop. But for some reason, yet to be analyzed, there are pending events preventing the process to exit on its own. A possible workaround is to call `process.exit()`.

_Originally posted by @nunoguedelha in https://github.com/ami-iit/yarp-openmct/issues/34#issuecomment-931748541_

**Comment by nunoguedelha** [comment]
The main problem with the server closure seems to come from the fact that if the telemetry server is created as follows:
```js
const telemServer = app.listen(portTelemetryRespOrigin, function () {
    console.log('ICubTelemetry History hosted at http://localhost:' + portTelemetryRespOrigin + '/history');
    console.log('ICubTelemetry Realtime hosted at ws://localhost:' + portTelemetryRespOrigin + '/realtime');
});
```
and for stopping it, we should do:
```js
telemServer.close(() => {
        console.log('iCub Telemetry Server closed. No further incoming requests accepted.');
    })
```
but the `close()` apparently does nothing (the debugger displays the function body as being `[native code]`), and we don't see the `unlisten` callback (previously returned by `ICubTelemetry.prototype.listen()`) being called.

Or maybe the event `close` is being send but not caught. Probably it has to do with the definition of `RealtimeServer(device)` constructor, which is using the `express` packet instead of `express-ws` (the later is wrapped with the websocket interface). To be checked tomorrow...

_Originally posted by @nunoguedelha in https://github.com/ami-iit/yarp-openmct/issues/34#issuecomment-933896226_

**Comment by nunoguedelha** [comment]
## Stop the Telemetry HTTP server `telemServer` from accepting new connections

- Use the `http.Server.close(callback)` method to stop the HTTP server from accepting new connections.
   https://nodejs.org/api/net.html#serverclosecallback
Stops the server from accepting new connections and keeps existing connections. This function is asynchronous, the server is finally closed when all connections are ended and the server emits a 'close' event. The optional callback will be called once the 'close' event occurs. Unlike that event, it will be called with an Error as its only argument if the server was not open when it was closed.

## Stop listening to client requests ("subscribe"/"unsubscribe" events) on the open websockets
...
