### ISSUE TITLE
Exit the main process after all closure steps are completed

### ISSUE THREAD

**Issue by nunoguedelha** [ami-iit/yarp-openmct#61]
### The Two Main Issues Addressed Here
- Some modules included in the main script may add listeners to the closure events SIGxxxx, which call `process.exit()` or any other procedure that we don't want being executed before the `terminationHandler` of the main application.
- The process should exit automatically if there is no pending queued events in the Node Event Loop. But for some reason, yet to be analyzed, there are pending events preventing the process to exit on its own. A possible workaround is to call `process.exit()`.

### References
Event Loop
https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#setimmediate-vs-settimeout
https://nodejs.dev/learn/the-nodejs-event-loop
https://nodejs.dev/learn/understanding-process-nexttick
https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop

### Avoiding a Premature Exit
- [x] Before even adding the listener to the a given closure signal (SIGINT, etc): (a) backup the existing listeners registered for that same signal, (b) remove them, (c) add our own listener `terminationHandler`, (d) restore the backuped listeners after completing `terminationHandler`. => #62 

### Workaround
- [x] Workaround: calling `process.exit()` after execution of subset C (very last). => #62 

### Further Analysis
- [x] ~Closing all the ports manually (instead of letting the on `exit` callback do it).~ => moved to #76 .
- [x] ~Checking the pending handles and requests in the Event Loop.~ => moved to #76 .

**Comment by nunoguedelha** [comment]
## Closing all the ports manually, and checking the pending handles and requests in the Event Loop :hourglass:

- Closing the ports
  https://github.com/ami-iit/yarp-openmct/commit/2952072f755cef70c5d97316f8ef66c53e55540d
- checking the pending handles and requests in the Event Loop
  [nodejs/node#1128](https://github.com/nodejs/node/issues/1128)
  https://github.com/thlorenz/active-handles
  In the last promise handling...
  https://github.com/ami-iit/yarp-openmct/blob/2952072f755cef70c5d97316f8ef66c53e55540d/iCubTelemVizServer/terminationHandler.js#L22-L29
  we use `process._getActiveHandles()` and `process._getActiveRequests()` to get the pending actions in the Event Loop.

**Comment by nunoguedelha** [comment]
## Avoiding a Premature Exit

Before even adding the listener to the a given closure signal (SIGINT, etc), we execute the following a the end of the main script:
- [ ] backup the existing listeners registered for that same signal,
- [ ] remove them,
- [ ] add our own listener `terminationHandler`.

After completing `terminationHandler`, so, after Subset C...
https://github.com/ami-iit/yarp-openmct/blob/b07deb537ee3513b16bd3a14115c469449d38ba9/iCubTelemVizServer/terminationHandler.js#L22-L27

...do:
- [ ] restore the backuped listeners.
- [ ] Add a listener which includes the workaround mentioned in the issue description. The listener is the last after the backuped listeners.
- [ ] Emit again the captured signal.
