### ISSUE TITLE
Missing plots measurement units: replace workaround by fix of nasa/openmct#4159

### ISSUE THREAD

**Issue by nunoguedelha** [ami-iit/yarp-openmct#82]
After cloning the Open-MCT repository and installing tag 1.7.8 (https://github.com/ami-iit/yarp-openmct/issues/81#issuecomment-971828190), I did some tests, importing a sample of the iCubTelemetry JSON dictionary as shown below, and noticed that **the measurement units are still missing**.

<details>
<summary>Test JSON dictionary</summary>

```json
{
  "openmct":{
    "0b0eae16-ac42-411c-8e23-ac392ddc3908":{
      "composition":[],
      "identifier": {
        "namespace": "yarpopenmct.telemetry",
        "key": "sens.imu"
      },
      "name": "iCub Telemetry",
      "type": "icubsensor.telemetry",
      "telemetry": {
        "values": [
          {
            "key": "value.ori.roll",
            "name": "Roll",
            "units": "degrees",
            "format": "float",
            "hints": {
              "range": 1
            }
          },
          {
            "key": "utc",
            "source": "timestamp",
            "name": "Timestamp",
            "format": "utc",
            "hints": {
              "domain": 1
            }
          }
        ]
      }
    }
  },
  "rootId":"0b0eae16-ac42-411c-8e23-ac392ddc3908"
}
```

</details>

So, while we wait for a fix from Open-MCT team, we will implement a simple workaround consisting in appending the units directly to the axis name.

_Originally posted by @nunoguedelha in https://github.com/ami-iit/yarp-openmct/issues/70#issuecomment-971839012_

**Comment by nunoguedelha** [comment]
Actually, the units are also missing in the expanded properties table on top of the plot canvas:
![image](https://user-images.githubusercontent.com/6848872/171903160-1c980613-400e-4bba-b021-ab8074fb4224.png)

The units we can see on the Y axis are the result of the workaround.

**Comment by nunoguedelha** [comment]
## Roadmap and Progress

### Open-MCT Current Status & Analysis Tools
- [x] Check status on the front end (https://github.com/nasa/openmct/issues/4159).
   => No update nor PR submitted.
   => Asked for news in issue.
- [x] Check if latest release still displays the same issue/limitations.
   => Same status on latest release `v2.0.3`.
- [x] Check VueJS plugin debuggability (#108 ).
   => Debugging on `Chrome (Developper mode and Vue DevTools)` or `WebStorm`.
   => Debug will be done on tag `v1.7.8-iit`.

### Issues Analysis
- [ ] Identify plugin component code related to the observed behaviour.
- [ ] Clearly understand the root cause.

### Fix/Workaround
- [ ] Design fix.
- [ ] Implement & test.

**Comment by nunoguedelha** [comment]
## Identify plugin component code related to the observed behaviour

Hovering over the pane HTML elements in the inspector window, we can see the respective highlighted areas within the expanded table above the plot.
<img width="2350" alt="image" src="https://user-images.githubusercontent.com/6848872/171905756-b5e2cf62-1c64-42dd-be61-b68cc49f1b43.png">

```html
<span class="plot-series-value cursor-hover hover-value-enabled"> 2022-06-03 16:14:04.146Z </span>
```

```html
<span class="plot-series-value cursor-hover hover-value-enabled">                  </span>
```

We can see that `Timestamp` and `Value` fields are configured as "plot-series-value cursor-hover hover-value-enabled".
